version: "3"

services:
    database:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        volumes:
            - databasedir:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: projects
        networks:
            - projects

    backend:
        build: backend
        ports:
            - 8080:8080
        depends_on:
            - database
        environment:
            - DATABASE_HOST=database
        networks:
            - projects

    frontend:
        build: frontend
        ports:
            - 3000:3000
        depends_on:
            - backend
        networks:
            - projects

volumes:
    databasedir: {}

networks:
    projects:
        driver: bridge